// select multilingual in this site
const translations = {
    en : {
        rouya: "Rouya",
        home: "Home",
        ourServices: "Our services",
        dropdownItem1: "Research and development",
        dropdownItem2: "networks",
        dropdownItem3: "Link between sites",
        dropdownItem4: "Backup",
        dropdownItem5: "Cloud computing",
        dropdownItem6: "cameras",
        dropdownItem7: "smart home",
        dropdownItem8: "Communication centers",
        dropdownItem9: "Security and protection",
        dropdownItem10: "Digital transformation",
        ourClients: "Our clients",
        aboutUs: "About us",
        contactUs: "Contact us",
        english: "English",
        arabic: "Arabic",
        textContent: "We exist to help people live better with artificial intelligence",
        explore: "Explore what services we offer",
        textPrag: "The company has many different departments, and each department provides a range of professional services",
        research: "Research and development services",
        provides: "The company provides the latest technical solutions through research and development",
        research2: "Network",
        provides2: "We install servers and supervise their operation, We install and enhance network hardware and We do wired and wireless network extension works",
        research3: "Link between sites",
        provides3: "We install the latest interconnection devices through the sites in order to connect all sites and branches in one secure network",
        research4: "Backup",
        provides4: "Believing in the importance of our customers information, we provide them with a secure backup service both within their network and on the cloud",
        research5: "Cloud Computing",
        provides5: "We provide cloud computing service to our customers in order for them to obtain servers with the latest technology remotely and to be fully secured. We will provide this service from the Kingdom of Saudi Arabia and after obtaining the necessary licenses for that",
        research6: "cameras",
        provides6: "We install and extend security cameras and home surveillance cameras, in accordance with the regulations of the Ministry of Interior and Industrial Security",
        research7: "smart homes",
        provides7: "We help individuals take advantage of the Internet speed in the Kingdom of Saudi Arabia by providing the latest Internet of Things technologies in order to develop their homes, control their devices wirelessly, and improve their performance.",
        research8: "Communication centers",
        provides8: "We install, extend and configure network phones to communicate with network members",
        research9: "Security and protection",
        provides9: "We provide our customers with firewall hardware to provide the highest level of network protection and control",
        solutionTitle:"We provide the best web design and web development solutions that have enabled global brands in Saudi Arabia to create digital experiences that matter",
        digitalExperience: "Digital experience solutions",
        solutions1: "How can we help",
        solutions2: "Choose your industry",
        solutions3: "Find out your needs",
        solutions4: "Enterprise Technologies",
        swiperBtn: "See all our services",
        h1: "Digital strategy",
        h2: "UI/UX Design",
        h3: "Web development",
        h4: "Immigration",
        h5: "DevOps",
        h6: "Digital marketing",
        h7: "Higher education",
        h8: "financial services",
        h9: "The shopping",
        h10: "Government",
        h11: "The media",
        h12: "Non-profit organizations and NGOs",
        h13: "Enterprise CMS",
        h14: "knowledge management",
        h15: "Marketing automation",
        h16: "Website search engine optimization",
        h17: "Managed Drupal Services",
        h18: "E-Commerce",
        h19: "Varbase",
        h20: "Uber Publisher",
        h21: "Marketing automation",
        h22: "Open Social",
        h23: "Vardoc",
        p1: "Align your business goals and technical requirements",
        p2: "Relevant user experience is based on insightful designs.",
        p3: "Simplify and deliver complex web development solutions.",
        p4: "Ongoing support and maintenance that ensures your digital growth and continuity.",
        p5: "Seamless and personalized across all channels for each website visitor.",
        p6: "Seamless and personalized across all channels for each website visitor.",
        p7: "Transforming into a digital academic experience.",
        p8: "Customized solutions for the digital economy and the customer.",
        p9: "Engage your customers across all channels and touch points.",
        p10: "Public service fits the digital age and the citizen.",
        p11: "Superior engagement and user experiences.",
        p12: "Boost your donations and expand your reach.",
        p13: "Empower your marketing and IT teams to deliver better performance.",
        p14: "Enhance communication and performance in all departments.",
        p15: "Deliver superior marketing campaign results across all channels.",
        p16: "Make sure your web pages rank first on search engines.",
        p17: "Reliable hosting, Drupal enabled, custom module development.",
        p18: "Have the best digital experience tailored to e-commerce.",
        p19: "Complete enterprise content management system and the world's most downloaded Drupal distribution.",
        p20: "The CMS is for businesses of content-heavy digital media, news, and entertainment platforms.",
        p21: "Develop customized campaigns that deliver superior results in minutes.",
        p22: "Grow your own social community and build lasting relationships with customers.",
        p23: "Enhance communication and collaboration within your organization with this customized, knowledge-based platform.",
        ourProcessP: "Our process",
        ourProcessH: "HOW WE DELIVER",
        ourProcessH3: "CLICK ON THE CIRCLE OR USE < > TO SHOW",
        processContent1: "Planning",
        processContent2: "Analysis",
        processContent3: "Design",
        processContent4: "Development",
        processContent5: "Testing",
        processContent6: "Deployment",
        processContent7: "Evaluation",
        processContent8: "Next Iteration",
        statisTicsP1: "projects delivered globally",
        statisTicsP2: "years of market experience",
        statisTicsP3: "global offices worldwide",
        statisTicsP4: "client base in world arab",
        statisTicsP5: "partners and alliances globally",
        statisTicsP6: "hospitality worldwide raning",
        WhyChooseH: "Why choose rouya",
        WhyChooseP: "We use the latest design and programming methods that aim to show your business in the best possible way, speed up the development process, and ensure that you get the best value for money",
        listChooseH4: "best price",
        listChooseP: "We at Rouya guarantee that you will get the products and services you are looking for at the best possible price compared to other competitors",
        listChooseH2: "Professionalism",
        listChooseP2: "The Rouya team is equipped with the highest level of professionalism and training that makes it possible to implement various ideas, no matter how difficult they are, such as programming games, using blockchain technologies and payment gateways",
        listChooseH3: "Arabic",
        listChooseH4: "Payment facilities",
        listChooseH5: "adequate support",
        listChooseP3: "The most important thing that distinguishes us in Rouya is that we speak your language, we understand you, and we understand what you are talking about. Make Arabic your primary language through the content writing and production team",
        listChooseP4: "To ensure the extent of credibility and excellence, we accept term payments for projects in order to achieve your ambition to start as soon as possible and with the least capital, and on the other hand, to prove our worth in implementation",
        listChooseP5: "Rouya services do not only depend on the implementation of ideas and projects from mobile and web applications, but also care about maintaining these works and ensuring their safety and free from any malfunctions",
        newsletterH3: "#Speak with Rouya",
        newsletterP: "Access the latest news and all things Rouya, including exclusive offers only through the Rouya newsletter",
        textContentClients: "The best clients",
        heroContentH2: "Contact us",
        heroContentH4: "Questions? inquiries? the support?",
        formDetailsSpan: "Hello",
        formDetailsH2: "We are glad to hear from you",
        formMessage: "send message",
        contactH1: "contact us",
        ourServicesHeroH2: "Our services",
        ourServicesHeroH4: "Everything in one place using the latest technologies",
        metaH2: "Techniques metavirus",
        metaP: "It is one of the divisions of Rouya company, and the service aims to transform the way users behave on the Internet by relying on meta virus or technologies beyond the world to carry out various activities that were carried out in a primitive way. At the state level as a whole and at the level of individuals",
        researchH2: "Research and development services",
        researchP: "The company provides the latest technical solutions through research and development in the following areas:",
        researchSpan1: "Artificial intelligence",
        researchSpan2: "Computer vision",
        researchSpan3: "Bots",
        researchSpan4: "Augmented reality",
        researchSpan5: "The Internet of things",
        researchSpan6: "3D printing",
        networksH2: "Network services",
        networksH4: "Extension and installation of networks",
        networksLi1: "We install servers and supervise their work",
        networksLi2: "We install and enhance network hardware",
        networksLi3: "We do wired and wireless network extension works",
        vpnH2: "Website linking services",
        vpnP: "We install the latest inter-site connectivity devices in order to connect all sites and branches into one secure network",
        BackupH2: "Backup services",
        BackupP: "Believing in the importance of our customers' information, we provide them with a secure backup service both within their network and on the cloud",
        cloudComputingH2: "Services Cloud",
        cloudComputingP: "It is one of the sections of the vision of a vision and it specializes in all the clouds .. In a vision, we consider that your work is our work and here to help your growth and start to convert your work towards the future through services and cloud solutions. to the cloud that efficiently meets your business needs and saves financial cost",
        securityCamerasH2: "Camera services",
        securityCamerasP: "We install and extend security cameras and home surveillance cameras, according to the regulations of the Ministry of Interior and Industrial Security",
        smartHomesH2: "Smart home services",
        smartHomesP: "We help individuals benefit from the speed of the Internet in the Kingdom of Saudi Arabia by providing the latest Internet of Things technologies in order to develop their homes, control their devices wirelessly and improve their performance",
        CommunicationCentersH2: "Call center services",
        CommunicationCentersP1: "We install, extend and configure network phones to communicate with network members",
        CommunicationCentersP2: "We also serve unified call centers for companies",
        SecurityH2: "Security Information",
        SecurityP: "It is one of the divisions of Rouya Company, and it mainly specializes in information security. It aims to secure information from hacking (i.e. unauthorized access). It aims to protect information from manipulation, such as deletion, modification, or even using it for purposes that may cause harm to data owners",
        experienceP: '"The experience and work of Vision and Visions clients made them stand out from the crowd. Nothing was impossible for this team."',
        TakeAdvantageOfStrengthH2: "Take advantage of our strength",
        TakeAdvantageOfStrengthSPAN: "Designing the perfect experience for an organization relies on the perfect blend of digital technologies, software, and assets designed to help it grow.",
        TakeAdvantageOfStrengthSPAN2: "Our Acquia certified team is consistently ranked among the top 10 providers of Drupal solutions for corporate website development in the world, and is renowned for its innovative approach to delivering projects aligned with business objectives.",
        webDevelopmentSolutionsH2: "Leading enterprise web development solutions",
        webDevelopmentSolutionsP: "Drupal is the leading technology of choice for companies and organizations looking to create meaningful experiences for their customers. Our Acquia-certified team of Drupal developers have a rich history of creating digital experiences across the healthcare, nonprofit, financial, higher education, and public services industries.",
        IntroducingNetworksH2: "Introducing networks",
        IntroducingNetworksText: "Networks are defined as a group of devices connected to each other through physical or wireless means of communication, allowing computers and individuals to share information, through chat rooms, e-mail, or sharing data and information using shared storage devices, printers, and also Sharing programs by running applications on remote computers, and the size of networks varies; It may consist of two computers connected with peripheral devices, or it may be huge data centers (Data centers) connected to each other, and it may also be a group of networks linked to each other, such as the Internet around the world.",
        NetworkFormsH2: "Network forms",
        NetworkFormsP: "The forms of computer networks differ in terms of the geometric arrangement in which they are installed, including:",
        NetworkFormsLI1: "The annular network",
        NetworkFormsLI2: "Hybrid network",
        NetworkFormsLI3: "Mesh or lattice networks",
        NetworkFormsLI4: "Stellar network",
        NetworkFormsLI5: "The tree network",
        NetworkFormsLI6: "Linear network",
        NetworkTypesH2: "Network types",
        NetworkTypesP: "Networks are divided according to their type into:",
        NetworkTypesLI1: "Home Networks: (HANs) is a network to connect the user's digital devices inside the home.",
        NetworkTypesLI2: "Local Area Networks: (LAN) connects computers that are geographically close to each other, such as devices in the same building.",
        NetworkTypesLI3: "Limited Area Network: (CAN) connects computers located within a small and specific geographical area, such as: a university campus, or a military base.",
        NetworkTypesLI4: "Wide Area Networks (WANs) connect remote computers via telephone lines or radio waves.",
        NetworkTypesLI5: "Regional Networks: MANs are a data network designed to connect cities.",
        NetworkBenefitsH2: "Networking benefits",
        NetworkBenefitsP: "There are many benefits of networks, including the following:",
        NetworkBenefitsLI1: "reduce the cost of resources; When computers are linked through a network, they can share various resources such as printers, operating systems, software, and others.",
        NetworkBenefitsLI2: "increase storage space; The data is stored in a huge shared space, such as a central server.",
        NetworkBenefitsLI3: "Flexibility to access data anywhere, through any device connected to the network.",
        NetworkBenefitsLI4: "simplify the communications process; Where it is possible to send and receive messages and files easily, once connected to the network.",
        vpnH3: "Website linking services",
        vpnH6: "We install the latest inter-site connectivity devices in order to connect all sites and branches into one secure network",
        IntroducingNetworksH2: "The concept of social networking sites",
        IntroducingNetworksText: "Social networking sites can be defined as a technology that facilitates the exchange of ideas and information through communication between virtual communities, and it relies mainly on the presence of the Internet connected to computers, tablets, or phones, and enables users to quickly access content that may be personal information, or documents, videos, or photos.",
        NetworkFormsH2: "The positives of social networking sites",
        NetworkFormsP: "Social networking sites provide many different benefits to users, including:",
        NetworkFormsLI1: "speed and ease of communication using applications; Which can be downloaded and installed on any type of mobile device and used anywhere and anytime.",
        NetworkFormsLI2: "Follow-up dedicated to news, events and topics; The user can customize what he follows on social media to get the content that suits and interests him, in addition to quick and direct access to news and information.",
        NetworkFormsLI3: "Follow-up dedicated to news, events and topics; The user can customize what he follows on social media to get the content that suits and interests him, in addition to quick and direct access to news and information.",
        NetworkFormsLI4: "Promote products and services, and expand their business to include the largest number of target audience through social media.",
        NetworkFormsLI5: "Having fun free time, during breaks and vacations",
        NetworkTypes2H2: "Disadvantages of social networking sites",
        NetworkTypes2P: "Despite the many positives of social media, there are many negatives that users of these sites face, including:",
        NetworkTypes2LI1: "invasion of privacy; The process of publishing everything related to the user on these sites may lead to a threat to his privacy, or may cause him many problems in life or work.",
        NetworkTypes2LI2: "cyber bullying and self-comparison; As many people suffer from a state of psychological pressure, tension, anxiety and even depression, as a result of what is published on these sites and comparing their reality with what they see, or they may become a target for people who may bully them through these sites and expl",
        NetworkTypes2LI3: "The loss of real interaction between people, and its replacement with online interaction; Many people may find online interaction an easy and convenient alternative to face-to-face interaction, which can isolate individuals from society.",
        NetworkTypes2LI4: "Attention Deficit; Using social media on phones may distract users, especially when they are doing other work and activities such as driving a car, which causes accidents.",
        NetworkTypes2LI5: "sleep irregularity; The light from electronic devices may disturb them during sleep, which may affect their productivity and activity during the following day.",
        backupH3: "Backup services",
        backupH5: "Believing in the importance of our customers' information, we provide them with a secure backup service both within their network and on the cloud",
        DefinitionOfBackupH3: "Definition of backup",
        DefinitionOfBackupSpan1: "A backup is the process of copying files or databases so that these copies are preserved in the event of equipment failure or an error. Backups are a routine part of most companies.",
        DefinitionOfBackupSpan2: "Not only business computer administrators. Backups are essential for PC users, but they are often neglected. Recovering files that you previously copied is called restoring them.",
        netH2: "Backup types",
        netLI1: "Full Backup: Full Backup is exactly as its name. It is a complete copy of the dataset. Although full backups can provide better protection, most organizations only use them on a periodic basis because they are time consuming and often require a large number of tapes or disks.",
        netLI2: "Incremental Backup: Since a full backup takes a very long time, incremental backups are designed to reduce the amount of time it takes to do the backup. An incremental backup means that only data that has changed since the previous backup is copied, but requires a full backup first to start working.",
        whoTextContent: "About Rouya",
        whoAreWeH1: "Who Are We",
        whoAreWeText: "A Saudi company working in the field of technology and information through the use of artificial intelligence techniques, computer vision, the use of robots, 3D printing, providing an augmented reality experience, managing, organizing and analyzing data, obtaining outputs through certain procedures that are forgotten according to the workflow mechanism, installing and extending network and communication services, camera monitoring systems and providing security services cyber",
        introMangH4: "Founder and director of the company",
        introMangP: "Engineer Hattan aims to develop information technology solutions through the use of artificial intelligence techniques, computer vision, the use of robots, 3D printing, and the provision of an augmented reality experience. Engineer Hattan Ashour holds a master's degree in information technology from the United States of America and has published a number of researches in these fields.",
        visionSectionH1: "Our vision",
        visionSectionP1: "Providing a vision for the future of technology from the heart of Saudi Arabia",
        visionSectionH2: "Our message",
        visionSectionP2: "Providing the latest information technology solutions to help our customers in their business and support the Kingdom's economy by providing the latest technologies and solutions",
        valuesSectionH1: "Rate us",
        valuesSectionLI1: "Creativity",
        valuesSectionLI2: "Win Win Situation",
        valuesSectionLI3: "Continuous Improvement",
        valuesSectionLI4: "Efficiency",
        valuesSectionLI5: "Discipline",
        advantagesTitle: "Advantages of cloud computing",
        advantageSpeedH3: "The speed",
        advantageSpeedH5span1: "Cloud services give you easy access to a wide range of technologies, so you can accelerate the pace of innovation and develop anything imaginable. You can quickly deploy resources whenever you need them—from infrastructure services like compute, storage, and databases, to the Internet of Things, machine learning, data warehousing and analytics, and more.",
        advantageSpeedH5span2: "Deploy technical services in minutes, and go from conceptualization to execution on large numbers of things more quickly than ever before. This gives you the freedom to experiment and test new ideas to provide a different customer experience and transform your business.",
        advantageFlexibileH3: "Flexibility",
        advantageFlexibileH5span: "When you use the cloud, you don't need to put in an excessive amount of upfront resource expenditure to handle future peak levels of business activity. Instead, you will save as much resources as you actually need. And you can instantly expand or shrink those resources to match your growing or shrinking production capabilities as your business needs change.",
        advantageCostSavingsH2: "Cost savings",
        advantageCostSavingsH5span: "Cloud services allow you to replace fixed expenses (such as data centers and physical servers) with variable expenses and only pay for IT based on how you use it. In addition, variable expenses are much lower than what you would pay on your own because of the savings associated with customization.",
        advantage_deployH2: "Deploy globally in minutes",
        advantage_deployH5span: "When you rely on cloud services, you can expand your business to new geographies and publish globally in minutes. For example, AWS has infrastructure all over the world, so you can deploy your application to many physical locations with just a few clicks. Making applications closer to end users reduces latency and improves the experience for end users.",
        typeTitle: "Types of cloud computing",
        advantageH1: "Infrastructure as a Service (IaaS)",
        advantageH2: "Platform as a Service (PaaS)",
        advantageH3: "Software as a Service (SaaS)",
        advantageP1: "IaaS encompasses the building blocks of IT in the cloud. They usually provide access to the benefits of networking, computers (whether in virtual environments or through dedicated hardware), and data storage spaces. IaaS services give you the highest level of flexibility and management control over all of your IT resources. It is very similar to the IT resources that many IT workers and developers are familiar with.",
        advantageP2: "PaaS removes the need for managing core infrastructure (typically hardware and operating systems) and allows you to focus on deploying and managing your applications. This helps you achieve greater efficiency, as you don't need to worry about resource procurement, capacity planning, software maintenance, debugging, or any of the other non-enterprise heavy burdens associated with running your application.",
        advantageP3: "SaaS provides you with a complete product that is operated and managed by the service provider. More often than not, when people mention SaaS they mean end-user applications (such as web-based email). With SaaS provisioning, you don't have to think about how to maintain service provision or how to manage the underlying infrastructure. All you need to think about is how you use that particular program.",
        TypesOfSurveillanceCameraSystemsH3: "Types of surveillance camera systems",
        TypesOfSurveillanceCameraSystemsH4: "Cameras transmit the captured signal in two ways, each with advantages and disadvantages. In our choice of a type, we depend on the conditions of the place, the working conditions of the camera, the distance from which the signal is transmitted, and the quality of the image to be captured",
        TypesOfSurveillanceCameraSystemsLi1: "IP Camera: It is a camera used to monitor some places using the Internet to transmit encrypted video.",
        TypesOfSurveillanceCameraSystemsLi2: "Wired system (cable system): It is a camera connected to wires and cables. This type has disadvantages, including the inability to extend the cable to all areas and the lack of freedom in choosing the installation location with the difficulty of moving cameras later.",
        TypesOfSurveillanceCameraSystemsLi3: "Wireless system: It is a surveillance camera without the use of wires or cables that uses Wi-Fi technology (this type is installed without the use of cables via the wireless router network and is monitored via the Internet and viewed from the smart phone, the ability to record on the computer with the infrared night vision feature)",
        TypesOfSurveillanceCameraSystemsLi4: "Hidden: It is an invisible camera for spying or security purposes without notice of targets.",
        TypesOfSurveillanceCameraSystemsLi5: "External: Surveillance cameras that are used in open areas and places.",
        TypesOfSurveillanceCameraSystemsLi6: "Indoor: These are cameras that are installed and used in closed areas that are not exposed inside buildings.",
        TypesOfSurveillanceCameraSystemsLi7: "Mobile: They are mobile cameras that work in all directions.",
        TypesCamerasH3: "Types of surveillance cameras",
        TypesCamerasH4: "Surveillance cameras differ in terms of shape, use, connection method, and purpose, including external, internal, mobile, and fixed cameras.",
        TypesCamerasLi1: "External cameras are surveillance cameras that are used in open areas and places, as they are characterized by their ability to withstand all types of weather and environmental and atmospheric factors from extreme heat and cold used to monitor the street or building from the outside.",
        TypesCamerasLi2: "Indoor cameras are cameras that are installed and used in closed areas that are not exposed inside buildings. And so she watches the buildings from the inside.",
        TypesCamerasLi3: "PTZ mobile cameras. These cameras are suitable for large areas, as they work in all directions, right and left, up and down. They can work in all directions and shoot on a large scale, and the ability to rotate up to 360 degrees horizontally and 90 degrees vertically.",
        TypesCamerasLi4: "Wireless cameras These cameras transmit the signal without wires and connect to the Internet via Wi-Fi and are used in places where cables cannot be extended.",
        TypesCamerasLi5: "IP network cameras, which are the modern type or the new generation, which are Internet Protocol cameras. Network cameras that are connected directly to the router of the Internet and transmit data over the network. They are connected with display and recording devices, and they are also cameras equipped with infrared rays for night surveillance.",
        features1H3: "Rationalization of energy consumption",
        features2H3: "A friend of the environment",
        features1H6: "The sensors in the smart home perform many tasks. For example, they are responsible for turning on the lights automatically when you enter the room and turning them off as soon as you leave. They also turn off the air conditioner and heater if the weather is suitable, in addition to stopping the work of many devices and systems if you go out or not. need to use it.",
        features2H6: "The advantages of a smart home also include preserving the environment, as many smart homes rely on the sun as a primary source of energy, not to mention reducing their use of fuel and electricity, which reduces environmental pollution.",
        featuresH2: "The most important features of the smart home",
        InformationSecurityFeaturesH2: "Information security features",
        InformationSecurityFeatures1H3: "Security and protection",
        InformationSecurityFeatures1H4: "Multifunctional sensors at the doors, windows, and inside the rooms in the smart home provide maximum protection. Most of the time, smart homes include many cameras distributed throughout, where you can monitor your home from anywhere in the world. The smart home also features a special system when traveling. , which works to turn the lights on and off and open and close the curtains, so that it appears to people outside that the house is not empty.",
        InformationSecurityFeatures2H3: "High safety scores",
        InformationSecurityFeatures2H4: "The smart home is built to comply with the highest levels of security and safety, and this is evident through fire detection sensors, as the home works to contact the civil defense or fire department in the event of a fire, and it also alerts you if there are spoiled foods in the refrigerator to get rid of.",
        basicPrinciplesH2: "Basic principles",
        principlesTitle1: "Confidentiality",
        principlesTitle2: "Integration (safety)",
        principlesTitle3: "Save data",
        principlesP1: "Confidentiality is the term used to prevent information from being disclosed to unauthorized persons. For example, the use of a credit card in commercial transactions on a network requires the entry of the credit card number to be transmitted from the buyer to the merchant and from the merchant to complete and process the transactions on the network. The system attempts to enforce confidentiality by encrypting the card number during transmission, by limiting access to places where the card number sequence is stored or shown (in databases, file history, backups, and printed receipts), by restricting access to places where the number and data are stored . But if the unauthorized party has obtained the card number in any way, then this is a violation of the principle of confidentiality in saving and storing data.",
        principlesP2: "In the field of information security, integrity (integrity) means preserving data from alteration or modification by unauthorized persons. When a person, intentionally or unintentionally, deletes, violates or damages the integrity of important data files, and is not authorized to do so, this is a violation of data integrity. When a virus infects a computer, and modifies or damages its data, this is a violation of data integrity, as well as when an (unauthorized) employee is able to modify his salary in the database and salaries, and when an (unauthorized) user sabotages a website, all of this is considered breach of data integrity. The integrity of the data also means that the changes in the data are steady, so when a bank customer withdraws or deposits, this should be reflected in his balance in the bank.",
        principlesP3: "Any information system aims to serve its purpose, for information to be available when it is needed. This means that the following system elements work properly and continuously",
        callCenterTechnologyTitle1: "Call center technology",
        callCenterTechnologyTitle2: "Patents",
        callCenterTechnologyTitle3: "Call center mechanisms",
        callCenterTechnology1H6: "Call center technology is subject to improvements and innovations. Some of these technologies include speech recognition and synthesis using computer programs to allow computers to handle the first level of customer support and assistance, text search and natural language processing for constructive interaction with customers and training of employees via robotic researcher on best practices from Back calls, and other techniques to improve employee productivity and increase customer satisfaction. Automated picking or automated routing also improves efficiency.",
        callCenterTechnology2H6: "There are a large number of patents covering different aspects of call center operations, automated systems, and technology. (Patented) One of the first inventors in this field was Katz A. Ronald holds more than 50 patents related to toll-free phone numbers, Auto Attendant, Automated Speech Distribution, Voice Response Module, Computer Telephony Integration and Speech Recognition.",
        callCenterTechnology3H6: "Communications are often divided into outgoing and received calls. Received communications are communications made by the consumer to obtain information, to report a defect, or to request assistance. Outgoing communications are significantly different from received communications, as the employee makes contacts with potential buyers with the intent Selling a product or providing a service to an individual. It is possible to combine incoming and outgoing campaigns, but this is not a common practice. Call center staff are often organized into a multi-level administrative system to achieve better efficiency in handling calls. The first level in this organizational model consists of the operators, who direct inquiries directly to the concerned department and provide general information from the directory.",
        digitalTransformationH2: "It is the change related to the application of digital technology to bring about a radical change in the way of work and to serve the beneficiaries faster and better.",
        AdvantagesOfDigitalTransformationH3: "Benefits and advantages of digital transformation",
        AdvantagesOfDigitalTransformationLi1: "Speed ​​up your daily workflow.",
        AdvantagesOfDigitalTransformationLi2: "Ease, speed and flexibility of applying new services.",
        AdvantagesOfDigitalTransformationLi3: "Increased quality and efficiency Secret work",
        AdvantagesOfDigitalTransformationLi4: "Reducing errors and spending.",
        AdvantagesOfDigitalTransformationLi5: "Increasing productivity and improving products.",
        AdvantagesOfDigitalTransformationLi6: "The possibility of taking advantage of modern technologies to develop performance, forecast and plan for the future.",
        AdvantagesOfDigitalTransformationLi7: "Raise levels of transparency and governance.",
        AdvantagesOfDigitalTransformationLi8: "Business and service continuity.",
        AdvantagesOfDigitalTransformationLi9: "Improve the quality of services provided to beneficiaries.",
        AdvantagesOfDigitalTransformationLi10: "Increase beneficiary satisfaction.",
        ChallengesAndPillarsH3: "Challenges and pillars of change for digital transformation",
        ChallengesAndPillarsLi1: "Safe digital transformation: to maintain the confidentiality, integrity and continuity of services and businesses.",
        ChallengesAndPillarsLi2: "Changing the organizational culture: There may be resistance to change. Cultural change is a preliminary process for any organizational change and development. This requires training and preparing employees for change.",
        ChallengesAndPillarsLi3: "Initiating digital transformation efforts by automating existing processes and procedures without fully understanding or agreeing on the definition of success of this process: strong management, the foundation of strong technology.",
        ChallengesAndPillarsLi4: "High level of expectations of beneficiaries in terms of the value they will get, and the experience they will throw: This requires having the structure, culture, organization, human resources, processes and technology",
        RequirementsAndStepsH2: "Requirements and steps for digital transformation",
        RequirementsAndSteps1H3: "Requirements",
        RequirementsAndSteps2H3: "Steps",
        RequirementsAndSteps1Li1: "Senior management support",
        RequirementsAndSteps1Li2: "Human competencies - an integrated and trained work team",
        RequirementsAndSteps1Li3: "Technical requirements (hardware and software)",
        RequirementsAndSteps2Li1: "Determine the digital transformation vision",
        RequirementsAndSteps2Li2: "Draw goals",
        RequirementsAndSteps2Li3: "Writing a digital transformation strategy",
        RequirementsAndSteps2Li4: "Divide the strategy into small projects that can be managed",
        theStrategyH3: "The National Strategy for Digital Transformation in the Kingdom of Saudi Arabia",
        theStrategyLi1: "The Kingdom of Saudi Arabia has adopted communications and information technology systems to reach an information society and a digital economy.",
        theStrategyLi2: "The strategy aims to achieve higher rates of well-being for citizens and residents, and to facilitate their lives.",
        theStrategyLi3: "In 2017, a permanent committee was established under the name of the National Committee for Digital Transformation",
        theStrategyLi4: "The Government E-Transactions Program (YERS) diagnoses the maturity of government agencies in government digital transformation.",
        offerCamera: "Camera",
        offerTitle: "Network recorder (NVR)",
        offerTitle2: "Indoor cameras",
        offerTitle3: "Outdoor cameras",
        offerDesc: "Dahua set of 8 indoor and outdoor surveillance cameras with a resolution of 2 mega pixels, day and night imaging, with a recording device that can be viewed from the mobile phone",
        offerBtn: "BUY",
        totalCart: "Total:",
    },
    ar : {
        rouya: "رؤية",
        home: "الصفحة الرئيسية",
        ourServices: "خدماتنا",
        dropdownItem1: "البحث والتطوير",
        dropdownItem2: "الشبكات",
        dropdownItem3: "الربط بين المواقع",
        dropdownItem4: "النسخ الاحتياطي",
        dropdownItem5: "الحوسبة السحابية",
        dropdownItem6: "الكاميرات",
        dropdownItem7: "المنازل الذكية",
        dropdownItem8: "مراكز الاتصالات",
        dropdownItem9: "الامن و الحماية",
        dropdownItem10: "التحول الرقمي",
        ourClients: "عملاؤنا",
        aboutUs: "من نحن",
        contactUs: "تواصل معنا",
        english: "الانجليزية",
        arabic: "العربية",
        textContent: "نحن موجودون لمساعدة الناس على العيش بشكل أفضل باستخدام الذكاء الاصطناعي",
        explore: "استكشف ماذا نقدم من خدمات",
        textPrag: "يتبـع للشركة العديـد مـن الأقســام المتنوعـة ويقــدم كل قســـم مجموعــة مــن الخدمـات الاحترافيـة",
        research: "خدمات البحث والتطوير",
        provides: "توفر الشركة أحدث الحلول التقنية وذلك من خلال الأبحاث والتطوير",
        research2: "الشبكات",
        provides2: "نقوم بأعمال تركيب أجهزة السيرفرات والإشراف على عملها و نقوم بتنصيب أجهزة الشبكات وتعزيزها و نقوم بأعمال تمديد الشبكات سلكيا ولاسلكيا",
        research3: "الربط بين المواقع",
        provides3: "نركب أحدث أجهزة الربط بين المواقع عن طريق وذلك من أجل ربط جميع المواقع والفروع في شبكة واحدة مؤمنة",
        research4: "النسخ الاحتياطي",
        provides4: "إيماناً بأهمية معلومات عملائنا نوفر لهم خدمة النسخ الاحتياطي الآمن سواءُ داخل شبكتهم وعلى الشبكة السحابية",
        research5: "الحوسبة السحابية",
        provides5: "نؤفر خدمة الحوسبة السحابية لعملائنا من أجل حصولهم على سيرفرات بأحدث التقنية عن بعد وتكون مؤمنة بالكامل وسنؤفر هذه الخدمة من المملكة العربية السعودية وبعد الحصول على التراخيص اللازمة لذلك",
        research6: "الكاميرات",
        provides6: "نقوم بتركيب وتمديد الكاميرات الأمنية وكاميرات المراقبة المنزلية وذلك وفق أنظمة وزارة الداخلية والأمن الصناعي",
        research7: "المنازل الذكية",
        provides7: "نساعد الأفراد على الاستفادة من سرعة الإنترنت في المملكة العربية السعودية وذلك عبر تقديم أحدث تقنيات إنترنت الأشياء من أجل تطوير منازلهم والتحكم بأجهزتهم لاسلكياً وتطوير أدائها",
        research8: "مراكز الاتصالات",
        provides8: "نقوم بتركيب وتمديد وتهيئة أجهزة هواتف الشبكات لتواصل أفراد الشبكة",
        research9: "الامن و الحماية",
        provides9: "نؤفر لعملائنا أجهزة جدار الحماية لتوفير أعلى مستوى من الحماية والتحكم لشبكة",
        solutionTitle:"نقدم أفضل حلول تصميم الويب وتطوير الويب التي مكنت العلامات التجارية العالمية في المملكة العربية السعودية من إنشاء تجارب رقمية مهمة",
        digitalExperience: "حلول الخبرة الرقمية",
        solutions1: "كيف يمكننا المساعدة",
        solutions2: "اختر الصناعة الخاصة بك",
        solutions3: "اكتشف احتياجاتك",
        solutions4: "تقنيات المؤسسة",
        swiperBtn: "شاهد كل خدماتنا",
        h1: "الإستراتيجية الرقمية",
        h2: "تصميم واجهة المستخدم / UX",
        h3: "تطوير الشبكة",
        h4: "الهجرة",
        h5: "DevOps",
        h6: "التسويق الرقمي",
        h7: "التعليم العالي",
        h8: "الخدمات المالية",
        h9: "التسوق",
        h10: "حكومة",
        h11: "وسائل الإعلام",
        h12: "المنظمات غير الربحية والمنظمات غير الحكومية",
        h13: "CMS للمؤسسات",
        h14: "إدارة المعرفة",
        h15: "أتمتة التسويق",
        h16: "تحسين محركات البحث في الموقع",
        h17: "خدمات دروبال المدارة",
        h18: "التجارة الإلكترونية",
        h19: "Varbase",
        h20: "Uber Publisher",
        h21: "أتمتة التسويق",
        h22: "Open Social",
        h23: "Vardoc",
        p1: "قم بمواءمة أهداف عملك والمتطلبات الفنية",
        p2: "تعتمد تجربة المستخدم ذات الصلة على التصاميم التي تعتمد على البصيرة.",
        p3: "تبسيط وتقديم حلول تطوير الويب المعقدة.",
        p4: "الترحيل الآمن إلى CMS متفوق يعمل على ترقية أدائك.",
        p5: "الدعم والصيانة المستمرة التي تضمن نموك الرقمي واستمراريتك.",
        p6: "سلس ومخصص عبر جميع القنوات لكل زائر لموقع الويب.",
        p7: "التحول إلى تجربة أكاديمية رقمي.",
        p8: "حلول مخصصة للاقتصاد الرقمي والعميل.",
        p9: "اجذب عملاءك عبر جميع القنوات ونقاط الاتصال.",
        p10: "الخدمة العامة تناسب العصر الرقمي والمواطن.",
        p11: "مشاركة فائقة وتجارب مستخدم.",
        p12: "عزز تبرعاتك ووسع مدى وصولك.",
        p13: "قم بتمكين فرق التسويق وتكنولوجيا المعلومات لديك لتقديم أداء أفضل.",
        p14: "تعزيز التواصل والأداء في جميع الأقسام.",
        p15: "تقديم نتائج حملة تسويقية فائقة عبر جميع القنوات.",
        p16: "تأكد من أن صفحات الويب الخاصة بك تحتل المرتبة الأولى على محركات البحث.",
        p17: "استضافة موثوق بها ، وتمكين دروبال ، وتطوير وحدة مخصصة.",
        p18: "امتلك أفضل تجربة رقمية مخصصة للتجارة الإلكترونية.",
        p19: "نظام إدارة المحتوى الكامل للمؤسسة وتوزيع Drupal الأكثر تنزيلًا على مستوى العالم.",
        p20: "CMS مخصصة للشركات للوسائط الرقمية والأخبار ومنصات الترفيه التي تعتمد على المحتوى الثقيل.",
        p21: "طور حملات مخصصة تحقق نتائج فائقة في دقائق.",
        p22: "قم بتنمية مجتمعك الاجتماعي الخاص بك وقم ببناء علاقات دائمة مع العملاء.",
        p23: "عزز التواصل والتعاون داخل مؤسستك باستخدام هذا النظام الأساسي المخصص القائم على المعرفة.",
        ourProcessP: "عمليتنا",
        ourProcessH: "كيف نقدم",
        ourProcessH3: "انقر على الدائرة أو استخدمها < > للعرض",
        processContent1: "تخطيط",
        processContent2: "تحليل",
        processContent3: "تصميم",
        processContent4: "تطوير",
        processContent5: "اختبارات",
        processContent6: "تعيين",
        processContent7: "تقييم",
        processContent8: "التكرار التالي",
        statisTicsP1: "تسليم المشاريع على مستوى العالم",
        statisTicsP2: "سنوات من الخبرة في السوق",
        statisTicsP3: "مكاتب عالمية في جميع أنحاء العالم",
        statisTicsP4: "قاعدة العملاء في العالم العربي",
        statisTicsP5: "شركاء وتحالفات على مستوى العالم",
        statisTicsP6: "ترتيب الضيافة في جميع أنحاء العالم",
        WhyChooseH: "لماذا تختار رؤية",
        WhyChooseP: "نستخدم احدث وسائل التصميم والبرمجة التي تهدف الي اظهار عملك في افضل شكل ممكن و تسريع عملية التطوير وضمان حصولك علي افضل قيمة مقابل سعر",
        listChooseH4: "افضل سعر",
        listChooseP: "نحن فى رؤية نضمن لك الحصول المنتجات والخدمات التي تبحث عنها بأفضل سعر ممكن مقارنا بغيرنا من المنافسين",
        listChooseH2: "الاحترافية",
        listChooseP2: "فريق عمل رؤية مجهز علي اعلي مستوي من الاحترافية والتدريب التي تجعل من الممكن تنفيذ مختلف الافكار مهما كانت درجة صعوبتها مثل برمجة الالعاب واستخدام تقنيات البلوك تشين وبوابات الدفع",
        listChooseH3: "اللغة العربية",
        listChooseH4: "تسهيلات السداد",
        listChooseH5: "الدعم الكافي",
        listChooseP3: "ن اهم ما يميزنا في رؤية اننا نتحدث بلغتك ونفهمك ونفهم ما تتطرق اليه, اجعل اللغة العربية لغتك الاساسية من خلال فريق كتابة وصناعة المحتوي",
        listChooseP4: "لضمان مدي المصداقية والتميز نقبل الدفع الأجل للمشاريع لنحقق طموحك في البدء في أسرع وقت وبأقل رأس مال وفي الناحية الاخري اثبات جدارتنا في التنفيذ",
        listChooseP5: "لا تتوقف خدمات رؤية علي فقط تنفيذ الافكار والمشاريع من تطبيقات الموبايل والويب ولكن ايضا تهتم بصيانة هذه الاعمال وضمان سلامتها وخلوها من اي اعطال",
        newsletterH3: "# تكلم مع رؤية",
        newsletterP: "الوصول إلى آخر الأخبار وكل ما يخص رؤية ، بما في ذلك العروض الحصرية فقط من خلال نشرة رؤية الإخبارية",
        textContentClients: "أفضل العملاء",
        heroContentH2: "تواصل معنا",
        heroContentH4: "أسئلة؟ استفسارات؟ الدعم؟",
        formDetailsSpan: "مرحبا",
        formDetailsH2: "نحن سعداء لسماعك",
        formMessage: "ارسل رسالة",
        contactH1: "اتصل بنا",
        ourServicesHeroH2: "خدماتنا",
        ourServicesHeroH4: "كل شيء في مكان واحد باستخدام أحدث التقنيات",
        metaH2: "تقنيات الميـتـا فيرس",
        metaP: "هــي إحـدى الأقســـام التـابعــة لشــركـة رؤية والخـدمـــة تهـدف إلى تحويـل الطريقـة التي يتصـرف بها المستخدميــن عبــر الإنترنت من خلال الاعتمـاد على الميتـا فيــرس أو تقنيــات مـا وراء العالم للقيام بالأنشطة المختلفة التي كانت تتم بطريقة بدائيــة وسوف تكون شركتنـا من أوائل الشركـات الرائـدة في تبنـى هـذه التقنيــة وتنفيذهـا والاستفـادة منهـا على مستـوى الدولـة ككـل ومستوى الأفراد",
        researchH2: "خدمات البحث والتطوير",
        researchP: "توفر الشركة أحدث الحلول التقنية وذلك من خلال الأبحاث والتطوير في المجالات التالية :",
        researchSpan1: "الذكاء الاصطناعي",
        researchSpan2: "الرؤية بالحاسب",
        researchSpan3: "الروبوتات",
        researchSpan4: "الواقع المعزز",
        researchSpan5: "انترنت الأشياء",
        researchSpan6: "الطباعة ثلاثية الابعاد",
        networksH2: "خدمات الشبكات",
        networksH4: "تمديد وتركيب الشبكات",
        networksLi1: "نقوم بأعمال تركيب أجهزة السيرفرات والإشراف على عملها",
        networksLi2: "نقوم بتنصيب أجهزة الشبكات وتعزيزها",
        networksLi3: "نقوم بأعمال تمديد الشبكات سلكيا ولاسلكيا",
        vpnH2: "خدمات الربط بين المواقع",
        vpnP: "نركب أحدث أجهزة الربط بين المواقع عن طريق وذلك من أجل ربط جميع المواقع والفروع في شبكة واحدة مؤمنة",
        BackupH2: "خدمات النسخ الاحتياطي",
        BackupP: "إيماناً بأهمية معلومات عملائنا نوفر لهم خدمة النسخ الاحتياطي الآمن سواءُ داخل شبكتهم وعلى الشبكة السحابية",
        cloudComputingH2: "الخـدمـات السـحابيــة",
        cloudComputingP: "هـــي إحـــدى الأقســام التـابعـــة لشــركــة رؤية وهــي متخصصــــة بكـل الخدمـــات السحـابيــة.. فـي رؤية نعتبـــر أن عملــك هــو عملنـــا ونحـن هنـا لمساعدتـك على النمـو والبـدء فـي تحويل عمـلك نحـو المستقبــل من خلال الخدمات والحلول السحابية يمكن لخبرائنا مساعدتـك فـي التصميــم الفعال وإنشاء البنية التحتية السحابيـة وتقديمهـا وإدارتهـا والحلـول المستندة إلى السحابة التي تلائم احتياجات عملك بكفاءة وتوفير التكلفـة الماليـة",
        securityCamerasH2: "خدمات الكاميرات",
        securityCamerasP: "نقوم بتركيب وتمديد الكاميرات الأمنية وكاميرات المراقبة المنزلية وذلك وفق أنظمة وزارة الداخلية والأمن الصناعي",
        smartHomesH2: "خدمات المنازل الذكية",
        smartHomesP: "نساعد الأفراد على الاستفادة من سرعة الإنترنت في المملكة العربية السعودية وذلك عبر تقديم أحدث تقنيات إنترنت الأشياء من أجل تطوير منازلهم والتحكم بأجهزتهم لاسلكياً وتطوير أدائها",
        CommunicationCentersH2: "خدمات مراكز الاتصالات",
        CommunicationCentersP1: "نقوم بتركيب وتمديد وتهيئة أجهزة هواتف الشبكات لتواصل أفراد الشبكة",
        CommunicationCentersP2: "كما نقوم بخدمة مراكز الاتصالات الموحدة للشركات",
        SecurityH2: "امن الامعلومات",
        SecurityP: "هــي إحـــدى الأقســـام التـابعـــة لشــركــة رؤية وتـختــص بشكل رئيسي في أمن المعلومات وتهدف إلى تأمين المعلومـات من الاختــراق (أي الوصـول غيــر المصـرح بـه) يهــدف إلـى حـمـايــة الـمـعـلـومــات مــن التـلاعــب بـهـا، كالحــذف أو التـعديــل أو حتـى استخدامها لأغراض قد تسبب ضرر على مالكي البيانات",
        experienceP: '"إن خبرة وعمل رؤية وعملاء رؤية جعلتهم يبرزون عن الآخرين. لم يكن هناك شيء مستحيل لهذا الفريق."',
        TakeAdvantageOfStrengthH2: "استفد من قوتنا",
        TakeAdvantageOfStrengthSPAN: "يعتمد تصميم التجربة المثاليّة للمؤسّسة على المزيج المثالي من التقنيات الرقمية والبرامج والأصول المصممة خصيصًا لمساعدتها على النمو.",
        TakeAdvantageOfStrengthSPAN2 : "تم تصنيف فريقنا المعتمد من Acquia على الدوام بأنه من بين أفضل 10 مزودي حلول دروپال لتطوير مواقع الويب للشركات في العالم، وهو مشهور بنهجه المبتكر في تسليم المشروعات تنضبط مع أهداف العمل.",
        webDevelopmentSolutionsH2: "حلول تطوير الويب الرائدة للمؤسسات",
        webDevelopmentSolutionsP: "دروبال هو التقنية الرائدة في اختيار الشركات والمؤسّسات التي تتطلع لخلق تجارب مفيدة لعملائها. يتمتع فريقنا المعتمد من Acquia من مطوري دروپال بتاريخ غني في إنشاء تجارب رقمية عبر قطاعات الرعاية الصحية، والمؤسسات غير الربحية، والمالية، والتعليم العالي، والخدمات العامة.",
        IntroducingNetworksH2: "التعريف بالشبكات",
        IntroducingNetworksText: "تُعرف شبكات الاتصال (Network) بأنّها مجموعة من الأجهزة المتّصلة ببعضها البعض من خلال وسائط اتصال ماديّة أو لاسلكيّة، تسمح لأجهزة الحاسوب والأفراد مشاركة المعلومات، وذلك من خلال غرف المحادثة، والبريد الإلكتروني، أو مشاركة البيانات والمعلومات باستخدام أجهزة التخزين المشتركة، أو الطابعات، وأيضاً مشاركة البرامج عن طريق تشغيل التطبيقات على أجهزة الحاسوب البعيدة، كما يختلف حجم الشبكات؛ فقد تتكون من جهازي حاسوب متصلان مع الأجهزة الطرفيّة، أو قد تكون مراكز بيانات ضخمة (Data centers) متصلة مع بعضها، وقد تكون أيضاً مجموعة من الشبكات المرتبطة مع بعضها البعض مثل الإنترنت الموجود في أنحاء العالم.",
        NetworkFormsH2: "اشكال الشبكات",
        NetworkFormsP: "تختلف أشكال شبكات الحاسوب من حيث الترتيب الهندسي الذي يتم تركيبها فيه، ومنها:",
        NetworkFormsLI1: "الشبكة الحلقيّة",
        NetworkFormsLI2: "الشبكة الهجينة",
        NetworkFormsLI3: "الشبكات المتداخلة أو الشَعريَّة",
        NetworkFormsLI4: "الشبكة النجميّة",
        NetworkFormsLI5: "الشبكة الشجريّة",
        NetworkFormsLI6: "الشبكة الخطيّة",
        NetworkTypesH2: "انواع الشبكات",
        NetworkTypesP: "تُقسم الشبكات حسب نوعها إلى:",
        NetworkTypesLI1: "الشبكات المنزليّة: (HANs) وهي شبكة لتوصيل الأجهزة الرقميّة الخاصة بالمُستخدِم داخل المنزل.",
        NetworkTypesLI2: "الشبكات المحليّة: (LAN) تربط أجهزة الحاسوب القريبة من بعضها البعض جغرافيّاً، كالأجهزة الموجودة في نفس المبنى.",
        NetworkTypesLI3: "شبكة المنطقة المحدودة: (CAN) تربط أجهزة الحاسوب الموجودة داخل منطقة جغرافية صغيرة ومحددة، مثل: حرم الجامعي، أو قاعدة العسكرية.",
        NetworkTypesLI4: "الشبكات الواسعة: (WANs) تربط أجهزة الحاسوب البعيدة عن طريق خطوط الهاتف، أو موجات الراديو.",
        NetworkTypesLI5: "الشبكات الإقليميّة: (MANs) وهي شبكة بيانات مصممة لربط المُدن.",
        NetworkBenefitsH2: "فوائد الشبكات",
        NetworkBenefitsP: "تتعدد فوائد الشبكات، ومنها ما يأتي:",
        NetworkBenefitsLI1: "تخفيض تكلفة الموارد؛ فعند ارتباط أجهزة الحاسوب من خلال الشبكة فإنه يمكنها مشاركة الموارد المختلفة مثل الطابعات، وأنظمة التشغيل والبرامج، وغيرها.",
        NetworkBenefitsLI2: "زيادة مساحة التخزين؛ حيث يتم تخزين البيانات في مساحة ضخمة مُشتركة، مثل خادم مركزي (central server).",
        NetworkBenefitsLI3: "المرونة في الوصول إلى البيانات في أي مكان، ومن خلال أي جهاز متصل بالشبكة.",
        NetworkBenefitsLI4: "تبسيط عمليّة الاتصالات؛ حيث يُمكن إرسال، واستقبال الرسائل، والملفات بسهولة، بمجرد الاتصال بالشبكة.",
        vpnH3: "خدمات الربط بين المواقع",
        vpnH6: "نركب أحدث أجهزة الربط بين المواقع عن طريق وذلك من أجل ربط جميع المواقع والفروع في شبكة واحدة مؤمنة",
        IntroducingNetworksH2: "مفهوم مواقع التواصل الاجتماعي",
        IntroducingNetworksText: "يُمكن تعريف مواقع التواصل الاجتماعي بأنَّها تقنيّة تُسهّل تبادل الأفكار والمعلومات من خلال التواصل بين المجتمعات الافتراضيَّة، وهي تعتمد بشكل رئيسي على وجود الإنترنت المُتصل بأجهزة الحاسوب، أو الأجهزة اللوحيَّة، أو الهواتف، وتُمكّن المستخدمين من الوصول بسرعة إلى المحتوى الذي قد يكون معلومات شخصيَّة، أو مستندات، أو مقاطع فيديو، أو صور.",
        NetworkFormsH2: "إيجابيات مواقع التواصل الاجتماعي",
        NetworkFormsP: "تُوفّر مواقع التواصل الاجتماعي العديد من الإيجابيَّات المختلفة للمُستخدمين ومنها:",
        NetworkFormsLI1: "السرعة والسهولة في التواصل باستخدام التطبيقات؛ التي يُمكن تنزيلها وتثبيتها على أي نوع من الأجهزة المحمولة واستخدامها في أيّ مكان وزمان.",
        NetworkFormsLI2: "المتابعة المُخصصة للأخبار والأحداث والمواضيع؛ إذ يُمكن للمُستخدِم تخصيص ما يتابعه على وسائل التواصل الاجتماعي ليحصل المحتوى الذي يُناسبه ويُثير اهتمامه، إضافةً إلى الوصول السريع والمباشر إلى الأخبار والمعلومات.",
        NetworkFormsLI3: "المتابعة المُخصصة للأخبار والأحداث والمواضيع؛ إذ يُمكن للمُستخدِم تخصيص ما يتابعه على وسائل التواصل الاجتماعي ليحصل المحتوى الذي يُناسبه ويُثير اهتمامه، إضافةً إلى الوصول السريع والمباشر إلى الأخبار والمعلومات.",
        NetworkFormsLI4: "الترويج للمُنتجات والخدمات، وتوسيع نطاق أعمالهم ليشمل أكبر عدد من الجمهور المُستهدف من خلال وسائل التواصل الاجتماعي.",
        NetworkFormsLI5: "قضاء وقت فراغ ممتع ، خلال أوقات الاستراحة والإجازات",
        NetworkTypes2H2: "سلبيات مواقع التواصل الاجتماعي",
        NetworkTypes2P: "بالرغم من الإيجابيات العديدة لوسائل التواصل الاجتماعي، إلا أنَّ هناك العديد من السلبيات التي تواجه مُستخدمي هذه المواقع، ومنها:",
        NetworkTypes2LI1: "انتهاك الخصوصيَّة؛ فعمليّة نشر كل شيء يخصّ المُستخدم على هذه المواقع قد تؤدي إلى تهديد خصوصيته، أو قد تُسبب له العديد من المشاكل في الحياة أو العمل.",
        NetworkTypes2LI2: "التنمر الإلكتروني (cyber bullying) ومقارنة النفس مع الآخرين؛ إذ يعاني العديد من الأشخاص من حالة من الضغط النفسيّ، والتوتر، والقلق وحتى الاكتئاب، نتيجة ما يتم نشره على هذه المواقع ومقارنة واقعهم مع ما يرونه، أو قد يصبحون هدفًا لأشخاص قد يتسلطون عليهم من خلال هذه المواقع ويستغلونهم.",
        NetworkTypes2LI3: "فقدان التفاعل الحقيقي بين الناس، واستبداله بالتفاعل عبر الإنترنت؛ ربما يجد الكثير من الناس أنَّ التفاعل عبر الإنترنت بديل سهل ومريح للتفاعل وجهًا لوجه، ممَّا قد يؤدي إلى انعزال الأفراد عن المجتمع.",
        NetworkTypes2LI4: "تشتت الانتباه؛ فاستخدام وسائل الاتصال الاجتماعي على الهواتف قد يتشتت انتباه المستخدمين، خاصَّة عند قيامهم بأعمال ونشاطات أخرى مثل قيادة السيارة، الأمر الذي يسبب الحوادث.",
        NetworkTypes2LI5: "عدم انتظام النوم؛ فالضوء الصادر من الأجهزة الإلكترونيًّة قد يُسبب اضطرابات لهم خلال النوم، ممَّا قد يؤثر على إنتاجيتهم ونشاطهم خلال اليوم اللاحق.",
        backupH3: "خدمات النسخ الاحتياطي",
        backupH5: "إيماناً بأهمية معلومات عملائنا نوفر لهم خدمة النسخ الاحتياطي الآمن سواءُ داخل شبكتهم وعلى الشبكة السحابية",
        DefinitionOfBackupH3: "التعريف بالنسخ الاحتياطي",
        DefinitionOfBackupSpan1: "النسخ الاحتياطي backup هو عملية لنسخ ملفات أو قواعد بيانات بحيث يتم الاحتفاظ بهذه النسخ في حالة تعطل المعدات أو حصول احد الاخطاء. النسخ الاحتياطي هو جزء روتيني في غالبية الشركات،",
        DefinitionOfBackupSpan2: "ليس فقط مسؤولي أجهزة الكمبيوتر التجارية. النسخ الاحتياطي ضروري لمستخدمي أجهزة الكمبيوتر الشخصية، ولكنها غالباً ما تهمل. ويسمى استرجاع الملفات restore التي قمت بنسخها سابقا استعادة لهم.",
        netH2: "انواع النسخ الاحتياطي",
        netLI1: "النسخ الاحتياطي الكامل: نسخة احتياطية كاملة تماما كما اسمها. أنها نسخة كاملة من مجموعة البيانات",
        netLI2: "النسخ الاحتياطي التزايدي: بما أن النسخ الاحتياطي الكامل يستغرق وقتاً طويلاً جداً، أتت النسخ الاحتياطية التزايدية لتقليل مقدار الوقت الذي يستغرقه للقيام بعملية النسخ الاحتياطي. نسخ احتياطي تزايدي يعني أنه يتم عمل نسخ فقط للبيانات التي تم تغييرها منذ النسخ الاحتياطي السابقة ولكن يتطلب أولا نسخة احتياطية كاملة للبدأ بالعمل.",
        whoTextContent: "نبذة عن رؤية",
        whoAreWeH1: "من نحن",
        whoAreWeText: "شركة سعودية تعمل في مجال التقنية و المعلومات عبر استخدام تقنيات الذكاء الاصطناعي ورؤية الحاسب واستخدام الروبوتات والطباعة ثلاثية الابعاد وتةفير تجربةالواقع المعزز وادارة وتنظيم وتحليل البيانات والحصول على المخرجات من خلال اجراءات معينة يتم انساؤها وفق الية سير العمل وتركيب وتمديد خدماتالشبكات والاتصالات وانظمة مراقبة الكاميرات وتوفير خدمات الامن السيبراني",
        introMangH4: "مؤسس ومدير الشركة",
        introMangP: "يهدف المهندس هتان إلى تطوير حلول تقنية المعلومات عبر استخدام تقنيات الذكاء الصناعي ورؤية الحاسب واستخدام الروبوتات والطباعة ثلاثية الأبعاد وتوفير تجربة الواقع المعزز، حصل المهندس هتان عاشور على ماجستير في تقنية المعلومات من الولايات المتحدة الأمريكية ونشر عدد من الأبحاث في هذه المجالات.",
        visionSectionH1: "رؤيتنا",
        visionSectionP1: "توفير رؤية لمستقبل التقنية من قلب السعودية",
        visionSectionH2: "رسالتنا",
        visionSectionP2: "تقديم أحدث حلول تقنية المعلومات لمساعدة عملائنا في أعمالهم ودعم اقتصاد المملكة من خلال توفير احدث التقنيات والحلول",
        valuesSectionH1: "قيمنا",
        valuesSectionLI1: "الإبداع",
        valuesSectionLI2: "المربح للجانبين",
        valuesSectionLI3: "التطوير المستمر",
        valuesSectionLI4: "الكفاءة",
        valuesSectionLI5: "الانضباط",
        advantagesTitle: "مزايا الحوسبة السحابية",
        advantageSpeedH3: "السرعة",
        advantageSpeedH5span1: "تتيح لك الخدمات السحابية إمكانية الوصول بسهولة إلى مجموعة واسعة النطاق من التقنيات، وبالتالي يمكنك التعجيل بوتيرة الابتكار وتطوير أي شيء يمكن تصوره. يمكنك استغلال الموارد بسرعة كلما احتجت إليها – بدءًا من خدمات البينة التحتية، مثل الحوسبة، والتخزين، وقواعد البيانات، ووصولاً إلى إنترنت الأشياء، وتعلم الآلة، ومخازن البيانات وتحليلاتها، والمزيد غير ذلك.",
        advantageSpeedH5span2: "يمكنك نشر الخدمات التقنية في غضون دقائق، والتحول من التصورات إلى التنفيذ فيما يتعلق بأعداد ضخمة من الأشياء بسرعة أكبر من ذي قبل. ويتيح لك ذلك حرية تجربة الأفكار الجديدة واختبارها لتوفير تجربة مختلفة للعملاء، وتحقيق التغيير في أعمالك.",
        advantageFlexibileH3: "المرونة",
        advantageFlexibileH5span: "عندما تستعين بالحوسبة السحابية، لن تحتاج إلى توفير قدر زائد من النفقات الأولية الخاصة بالموارد للتعامل مع مستويات الذروة في النشاط التجاري في المستقبل. فبدلاً من ذلك، ستوفر من الموارد المقدار الذي تحتاجه بالفعل. ويمكنك توسيع نطاق تلك الموارد أو تقليصه على الفور بما يتناسب مع القدرات الإنتاجية المتنامية أو المتقلصة كلما احتجت في نشاطك التجاري للتغيير.",
        advantageCostSavingsH2: "وفورات التكاليف",
        advantageCostSavingsH5span: "تتيح لك الخدمات السحابية إمكانية استبدال المصروفات الثابتة (مثل مراكز البيانات والخوادم الفعلية) بمصروفات متغيرة وعدم الدفع مقابل تكنولوجيا المعلومات إلا حسب استخدامك لها. وبالإضافة إلى ذلك، فإن المصروفات المتغيرة تقل بكثير مقارنةً بما كنت ستدفعه عند الاعتماد على نفسك بسبب فرص التوفير المرتبطة بالمواءمة مع الاحتياجات. ",
        advantage_deployH2: "النشر عالميًا في غضون دقائق",
        advantage_deployH5span: "عند الاعتماد على الخدمات السحابية، يمكنك التوسع في نشاطك ليشمل مناطق جغرافية جديدة والنشر علي مستوى عالمي في دقائق. فعلى سبيل المثال، تمتلك AWS بنية تحتية في مختلف أنحاء العالم، وبالتالي يمكنك نشر تطبيقك في العديد من المواقع الفعلية بمجرد عدد قليل من الضغطات. إن إتاحة التطبيقات في مكان أقرب للمستخدمين النهائيين يقلل من تأخر الاستجابة ويحسِّن من التجربة التي يحظى بها المستخدمون النهائيون.",
        typeTitle: "أنواع الحوسبة السحابية",
        advantageH1: "البنية التحتية كخدمة (IaaS)",
        advantageH2: "النظام الأساسي كخدمة (PaaS)",
        advantageH3: "البرامج كخدمة (SaaS)",
        advantageP1: "تشمل IaaS الركائز الأساسية لتكنولوجيا المعلومات في السحابة. فعادةً ما تتيح إمكانية الاستفادة من مزايا الشبكات، وأجهزة الكمبيوتر (سواء كانت في بيئات افتراضية أو من خلال أجهزة مخصصة)، ومساحات تخزين البيانات. وتتيح لك خدمات IaaS أعلى مستوى من المرونة والتحكم الإداري في كل موارد تكنولوجيا المعلومات الخاصة بك. وهي تشبه إلى حد كبير موارد تكنولوجيا المعلومات المألوفة للكثير من العاملين في أقسام تكنولوجيا المعلومات والمطورين بها.",
        advantageP2: "إن خدمة PaaS تجعلك في غنى عن إدارة البنية التحتية الأساسية (عادةً الأجهزة وأنظمة التشغيل) وتسمح لك بالتركيز على نشر تطبيقاتك وإدارتها. ويساعدك ذلك في تحقيق قدر أكبر من الكفاءة، إذ أنك لا تحتاج إلى القلق بشأن تدبير الموارد أو التخطيط للسعة أو صيانة البرامج أو تصحيح الأخطاء أو أي من الأعباء الثقيلة الأخرى التي لا تضيف إلى نجاح المؤسسة والمرتبطة بتشغيل تطبيقك.",
        advantageP3: "توفر لك خدمة SaaS منتجًا مكتملاً يتم تشغيله وإدارته من قبل مقدِّم الخدمة. وفي أغلب الأحيان، فإن الأشخاص عندما يذكرون خدمة SaaS يعنون التطبيقات المقدمة للمستخدم النهائي (مثل البريد الإلكتروني المعتمد على الويب). وبفضل توفير خدمة SaaS، فإنك لا تضطر إلى التفكير في كيفية الحفاظ على توفير الخدمة أو كيفية إدارة البنية التحتية الأساسية. فكل ما تحتاج إلى التفكير فيه هو كيفية استخدامك لذلك البرنامج على وجه الخصوص. ",
        TypesOfSurveillanceCameraSystemsH3: "أنواع أنظمة كاميرات المراقبة",
        TypesOfSurveillanceCameraSystemsH4: "نقل الكاميرات الإشارة التي يتم التقاطها بطريقتين ولكل نوع منهما مزايا وعيوب. نعتمد في اختيارنا لنوع ما على ظروف المكان وظروف عمل الكاميرا والمسافة التي تنقل منها الإشارة وجودة الصورة المراد التقاطها",
        TypesOfSurveillanceCameraSystemsLi1: "أي بي كاميرا: وهي كاميرا تستعمل لمراقبة بعض الأمكنة مستعملة الإنترنت لنقل الفيديو الدي يكون مشفرا.",
        TypesOfSurveillanceCameraSystemsLi2: "النظام السلكي (نظام الكابلات): وهي  كاميرا متصلة بأسلاك وكابلات، لهذا النوع عيوب منها عدم إمكانية مد الكابل إلى جميع المناطق وعدم الحرية في اختيار مكان التركيب مع صعوبة نقل الكاميرات فيما بعد.",
        TypesOfSurveillanceCameraSystemsLi3: "لنظام اللاسلكي: وهي كاميرا مراقبة دون استخدام أسلاك أو كابلات تستخدم تقنية الواي فاي (يتم تركيب هذا النوع دون استخدام كابلات عن طريق شبكة الموجه اللاسلكية ويتم مراقبتها عن طريق الإنترنت ومشاهدتها من الهاتف الذكى، إمكانية التسجيل على الكمبيوتر مع خاصية الرؤية الليلية الأشعة تحت الحمراء)",
        TypesOfSurveillanceCameraSystemsLi4: "المخفية: وهي كاميرا غير مرئية لأغراض التجسس أو الحامية بدون إشعار للأهداف.",
        TypesOfSurveillanceCameraSystemsLi5: "الخارجية: هي كاميرات المراقبة التي يتم استخدامها في المناطق والأماكن المكشوفة.",
        TypesOfSurveillanceCameraSystemsLi6: "الداخلية: هي الكاميرات التي يتم تركيبها واستخدامها في المناطق المغلقة الغير مكشوفة داخل الأبنية.",
        TypesOfSurveillanceCameraSystemsLi7: "المتحركة: هي كاميرات متحركة فهى تعمل في جميع الاتجاهات.",
        TypesCamerasH3: "أنواع كاميرات المراقبة",
        TypesCamerasH4: "تختلف كاميرات المراقبة من حيث الشكل والاستخدام وطريقة التوصيل والغرض فمنها الخارجى والداخلى والمتحرك والثابت.",
        TypesCamerasLi1: "كاميرات خارجية هي كاميرات المراقبة التي يتم استخدامها في المناطق والأماكن المكشوفة  حيث انها تتميز بقدرتها على تحمل جميع أنواع الطقس والعوامل البيئية والجوية من حرارة شديدة وبرودة تستخدم في مراقبة الشارع أو المبنى من الخارج.",
        TypesCamerasLi2: "كاميرات داخلية هي الكاميرات التي يتم تركيبها واستخدامها في المناطق المغلقة الغير مكشوفة داخل الأبنية. ولذا فهى تراقب المباني من الداخل.",
        TypesCamerasLi3: "كاميرات متحركة PTZ  وهذه الكاميرات تصلح للمساحات الواسعة حيث انها تعمل في جميع الاتجاهات يمينا ويسارا إلى اعلى وإلى اسفل، تستطيع العمل في جميع الاتجاهات والتصوير على نطاق واسع والقدرة على الدوران تصل إلى 360 درجة أفقيا و90 درجة راسي",
        TypesCamerasLi4: "كاميرات لاسلكية Wireless تنقل هذه الكاميرات الإشارة دون اسلاك وتتصل بشبكة النت عن طريق الواى فاى وتستخدم في الاماكن التي لا يمكن مد كابلات لها",
        TypesCamerasLi5: "كاميرات شبكية IP وهي النوع الحديث أو الجيل الجديد وهي كاميرات بروتوكول الإنترنت. كاميرات شبكية يتم توصيلها بشكل مباشر على الموجه الخاصة بالانترنت وتنقل البيانات عبر الشبكة.يتم توصيلها مع أجهزة عرض وتسجيل وهي أيضا كاميرات مجهزة بالأشعة تحت الحمراء والمخصصة للمراقبة الليلية.",
        features1H3: "ترشيد استهلاك الطاقة",
        features2H3: "صديق للبيئة",
        features1H6: "تقوم المستشعرات الموجودة في البيت الذكي بالعديد من المهام، فهي مسؤولة مثلاً عن إشعال الإنارة تلقائياً عند دخولك الغرفة، وإطفائها فور خروجك، كما وتقوم بإيقاف عمل المكيّف والمدفأة في حال كان الطقس مناسباً، بالإضافة إلى إيقاف عمل العديد من الأجهزة والأنظمة في حال خروجك أو عدم الحاجة لاستخدامها.",
        features2H6: "تشمل مميزات البيت الذكي أيضاً الحفاظ على البيئة، فالعديد من البيوت الذكية تعتمد على الشمس كمصدر أساسي للطاقة، ناهيك عن تقليل استخدامها للوقود والكهرباء، ما يحد من التلوث البيئي.",
        featuresH2: "أهم مميزات البيت الذكي",
        InformationSecurityFeaturesH2: "مميزات امن المعلومات",
        InformationSecurityFeatures1H3: "الأمان والحماية",
        InformationSecurityFeatures1H4: "تعمل المستشعرات متعددة الوظائف عند الأبواب والنوافذ وداخل الغرف في البيت الذكي على توفير أقصى درجات الحماية، وفي معظم الأحيان تضم المنازل الذكية العديد من الكاميرات الموزعة في جميع أرجائه، حيث يمكنك مراقبة منزلك من أي مكان في العالم، كما ويتميز البيت الذكي بنظام خاص عند السفر، والذي يعمل على تشغيل وإطفاء المصابيح وفتح وإغلاق الستائر، حتى يبدو للأشخاص في الخارج أن المنزل ليس فارغاً.",
        InformationSecurityFeatures2H3: "درجات سلامة عالية",
        InformationSecurityFeatures2H4: "يتم بناء البيت الذكي ليتماشى مع أعلى درجات الأمن والسلامة، ويتضح ذلك من خلال مستشعرات كشف الحرائق، حيث يعمل المنزل على الاتصال بقسم الدفاع المدني أو الإطفاء في حال نشوب حريق، كما يقوم بتنبيهك في حال وجود أطعمة فاسدة في الثلاجة للتتخلص منها.",
        basicPrinciplesH2: "المبادئ الاساسية",
        principlesTitle1: "السرية",
        principlesTitle2: "التكامل (السلامة)",
        principlesTitle3: "توفير البيانات",
        principlesP1: "السرية هو المصطلح المستخدم لمنع الكشف عن معلومات لأشخاص غير مصرح لهم بالأطلاع عليها أو الكشف عنها. على سبيل المثال، استعمال بطاقة الائتمان في المعاملات التجارية على شبكة يتطلب إدخال رقم بطاقة الائتمان على أن تنتقل من المشتري إلى التاجر ومن التاجر لإنجاز وتجهيز المعاملات على الشبكة. يحاول النظام فرض السرية عن طريق تشفير رقم البطاقة أثناء الإرسال، وذلك بالحد من الوصول إلى أماكن تخزين أو ظهور تسلسل رقم البطاقة (في قواعد البيانات، وسجل الملفات، النسخ الاحتياطي، والإيصالات المطبوعة)، وذلك بتقييد الوصول إلى الأماكن التي يتم تخزين الرقم والبيانات بها. اماإذا كان الطرف غير المصرح له قد حصل على رقم البطاقة بأي شكل من الأشكال فإن ذلك يعد انتهاكا لمبدأ السرية في حفظ وتخزين البيانات",
        principlesP2: "في مجال أمن المعلومات، التكامل (السلامة) يعني الحفاظ على البيانات من التغيير أوالتعديل من الأشخاص غير المخولين بالوصول اليها. عندما يقوم شخص، بقصد أو بغير قصد، بحذف أو انتهاك سلامة ملفات البيانات الهامة أو الإضرار بها، وهو غير مخول بذلك، يعد هذا انتهاكا لسلامة البيانات. وعندما يصيب فيروس حاسوبا، ويقوم بتعديل بياناته أو يتلفها يعد هذا انتهاكا لسلامة البيانات، وكذلك عندما يكون الموظف (غير المخول) قادرا على تعديل راتبه في قاعدة البيانات والمرتبات، وعندما يقوم مستخدم (غير مصرح له) بتخريب موقع على شبكة الإنترنت، كل ذلك يعد انتهاكا لسلامة البيانات. و تعني سلامة البيانات كذلك، أن تكون التغيرات في البيانات مطردة، فعندما يقوم عميل البنك بسحب أو إيداع، ينبغي أن ينعكس ذلك على رصيده في البنك.",
        principlesP3: "يهدف أي نظام للمعلومات لخدمة غرضه، أن تكون المعلومات متوفرة عند الحاجة إليها. وهذا يعني أن تعمل عناصر النظام الآتية بشكل صحيح ومستمر",
        callCenterTechnologyTitle1: "تقنية مركز الاتصالات",
        callCenterTechnologyTitle2: "براءات الاختراع",
        callCenterTechnologyTitle3: "آليات مراكز الاتصال",
        callCenterTechnology1H6: "تقنية مركز الاتصالات تخضع للتحسينات والابتكارات.بعض هذه التقنيات تشمل تمييزالكلام وتوليفه باستخدام برامج الحاسب الآلي للسماح للحواسيب للتعامل مع المستوى الأول من مستويات دعم ومعاونة العملاء، والبحث في النصوص ومعالجة اللغة الطبيعية وذلك للتفاعل البناء مع العملاء ولتدريب الموظفين عن طريق الباحث الآلى على أفضل الممارسات من المكالمات السابقة، وغيرها من التقنيات لتحسين إنتاجية الموظفين والارتفاع بمستوي رضا العملاء. يؤدي الانتقاء الآلي أو التوجيه الآلي إلى تحسين الكفاءة أيضا،",
        callCenterTechnology2H6: "هناك عدد كبير من براءات الاختراع التي تغطي جوانب مختلفة من عمليات مراكز الاتصال، والأنظمة الآلية، والتقنية. (براءة اختراع) واحد من أوائل المخترعين في هذا المجال هو كا تز أ. رونالد الذي لديه أكثر من 50 براءة اختراع متعلقة بأرقام الهاتف المجانية، والمصاحب الآلي، والتوزيع الآلي للكلام، ووحدة الاستجابة الصوتية، والتكامل الحاسوبى الهاتفي التكامل وتمييز الكلام.",
        callCenterTechnology3H6: "في كثير من الأحيان تنقسم الاتصالات لمكالمات صادرة وأخرى مستلمة.الاتصالات المستلمة هي اتصالات يجريها المستهلك للحصول على المعلومات، أو للإبلاغ عن وجود خلل، أو لطلب المساعدة.اما الاتصالات الصادرة فهي تختلف اختلافا كبيرا عن الاتصالات المستلمة، حيث يجرى الموظف الأتصالات مع المشترين المحتملين بنية بيع منتج ما أو تقديم خدمة للفرد. ومن الممكن الجمع بين حملات الاتصالات المستلمة والصادرة ولكن ليس هذا ممارسة شائعة. موظفو مراكز الاتصال في كثير من الأحيان يتم تنظيمهم في نظام إداري متعدد المستويات لتحقيق كفاءة أفضل في التعامل مع المكالمات.المستوى الأول في هذا النموذج التنظيمى يتكون من المشغلين، الذين يوجهون الاستفسارات مباشرة إلى الإدارة المعنية ويقدمون معلومات عامة من الدليل.",
        digitalTransformationH2: "هو التغري الرمتبط بتطبيق التكنولوجيا الرقمية إلحداث تغري جذري في طريقة العمل و لخدمة المستفيدين بشكل أرسع وأفضل.",
        AdvantagesOfDigitalTransformationH3: "فوائد ومزايا التحول الرقمي",
        AdvantagesOfDigitalTransformationLi1: "ترسيع طريقة العمل اليومية.",
        AdvantagesOfDigitalTransformationLi2: "سهولة ورسعة ومرونة تطبيق خدمات جديدة العمل.",
        AdvantagesOfDigitalTransformationLi3: "زيادة جودة وكفاءة سري",
        AdvantagesOfDigitalTransformationLi4: "تقليل األخطاء واإلنفاق.",
        AdvantagesOfDigitalTransformationLi5: "زيادة الانتاجية وتحسني المنتجات.",
        AdvantagesOfDigitalTransformationLi6: "إمكانية االستفادة من التقنيات الحديثة لتطوير األداء والتنبؤ والتخطيط للمستقبل.",
        AdvantagesOfDigitalTransformationLi7: "رفع مستويات الشفافية والحوكمة",
        AdvantagesOfDigitalTransformationLi8: "استرمارية األعمال والخدمات",
        AdvantagesOfDigitalTransformationLi9: "تحسني جودة الخدمات المقدمة للمستفيدين",
        AdvantagesOfDigitalTransformationLi10: "زيادة رضا المستفيدين",
        ChallengesAndPillarsH3: "التحديات وأركان التغيير للتحول الرقمي",
        ChallengesAndPillarsLi1: "التحول الرقمي الآمن: للحفاظ على سرية وسالمة واستمرارية الخدمات واألعمال.",
        ChallengesAndPillarsLi2: "تغيري الثقافة التنظيمية: قد يكون هنالك مقاومة للتغيري، التغيري الثقافي هي عملية تمهيدية ألي تغيري وتطوير تنظيمي، يتطلب ذلك تدريب وتهيئة الموظفني للتغيري",
        ChallengesAndPillarsLi3: "البدء في جهود التحول الرقمي من خالل أتمتة العمليات واإلجراءات الحالية، دون الفهم الكامل أو التوافق على تعريف نجاح هذه العملية: اإلدارة القوية، أساس لتقنية قوية",
        ChallengesAndPillarsLi4: " ارتفاع مستوى توقعات المستفيدين من ناحية القيمة اليت سيحصلون عليها، والتجربة اليت سيرمون بها : ذلك يتطلب امتالك البنية والثقافة والتنظيم والموارد البرشية والعمليات والتكنولوجيا",
        RequirementsAndStepsH2: "متطلبات وخطوات التحول الرقمي",
        RequirementsAndSteps1H3: "المتطلبات",
        RequirementsAndSteps2H3: "الخطوات",
        RequirementsAndSteps1Li1: "دعم الادارة العليا",
        RequirementsAndSteps1Li2: "كفاءات برشية – فريق عمل متكامل ومدرب",
        RequirementsAndSteps1Li3: "متطلبات تقنية )األجهزة والربامج)",
        RequirementsAndSteps2Li1: "تحديد رؤية التحول الرقمي",
        RequirementsAndSteps2Li2: "رسم الاهداف",
        RequirementsAndSteps2Li3: "كتابة اسرتاتيجية التحول الرقمي",
        RequirementsAndSteps2Li4: "تقسيم الاسرتاتيجية إلى مشاريع صغرية يمكن إدارتها",
        theStrategyH3: "الاستراتيجية الوطنية للتحول الرقمي في المملكة العربية السعودية",
        theStrategyLi1: "تبنت المملكة العربية السعودية أنظمة الاتصاالت وتقنية المعلومات للوصول إلى مجتمع معلوماتي واقتصاد رقمي.",
        theStrategyLi2: "تهدف االسرتاتيجية لتحقيق معدالت عليا من الرفاهية للمواطن والمقيم وتسهيل أمور حياتهم المعيشية.",
        theStrategyLi3: "في 2017 ،أنشئت لجنة دائمة باسم اللجنة الوطنية للتحول الرقمي.",
        theStrategyLi4: "يقوم برنامج التعامالت االلكرتونية الحكومية (يرس) بتشخيص مدى نضج الجهات الحكومية في التحول الرقمي الحكومي.",
        offerCamera: "كاميرا",
        offerTitle: "جهاز تسجيل شبكة (NVR)",
        offerTitle2: "كاميرات داخلية",
        offerTitle3: "كاميرات خارجية",
        offerDesc: "داهوا مجموعة من 8 كاميرات مراقبة داخلية وخارجية بدقة 2 ميغا بيكسل ، تصوير نهاري وليلي ، مع جهاز تسجيل يمكن مشاهدته من الهاتف المحمول",
        offerBtn: "شراء",
        totalCart: "المجموع:",
    },
};

const select = document.querySelector('#language-selector');
select.addEventListener("change", (e) => {
    setLanguage(e.target.value);
    localStorage.setItem('lang', e.target.value);
});

document.addEventListener('DOMContentLoaded', () => {
    const language = localStorage.getItem('lang') || 'en';
    setLanguage(language);
});

const setLanguage = (language) => {
    const elements = document.querySelectorAll('[data-lang]');
    elements.forEach((element) => {
        const translationKey = element.getAttribute('data-lang');
        element.textContent = translations[language][translationKey];
    });
    document.dir = language === 'ar' ? 'rtl' : 'ltr';
};




/* select navigation */
window.addEventListener('scroll', ()=> {
    let navbar = document.querySelector('.navbar');
    navbar.classList.toggle('sticky', window.scrollY > 150);
});
/* create open and close in navBar media query */
let navbarToggler = document.querySelector('.navbar-toggler');
let iconBar = document.querySelector('.fa-bars');
let navbarNav = document.querySelector('.navbar-nav');
navbarToggler.addEventListener('click' , ()=> {
    iconBar.classList.toggle('fa-xmark');
    navbarNav.classList.toggle('active');
});




/* select solutions section */
let tabs = document.querySelectorAll('.tabs p');
let tabsArr = Array.from(tabs);
let tabsContent = document.querySelectorAll('.tabs-content > .solution');
let tabsContentArr = Array.from(tabsContent);

tabsArr.forEach (ele => {
    ele.addEventListener('click', e => {
        tabsArr.forEach (elem => {
            elem.classList.remove('active');
        });

        e.currentTarget.classList.add('active');

        tabsContentArr.forEach (elem => {
            elem.style.display = 'none';
        });

        let dataset = document.querySelector(e.currentTarget.dataset.content);
        dataset.style.display = 'block';
    });
});




/* select ourProcess section for circular */
let icon = document.querySelectorAll('.icon .iBx');
let iconARR = Array.from(icon);
let processContent = document.querySelectorAll('.content > .contentBx');
let processContentARR = Array.from(processContent);

iconARR.forEach(element => {
    element.addEventListener('click', e => {
        iconARR.forEach(elem => {
            elem.classList.remove('active');
        });
        e.currentTarget.classList.add('active');
        processContentARR.forEach(elem => {
            elem.style.display = 'none';
        });
        let datasetCercle = document.querySelector(e.currentTarget.dataset.class);
        datasetCercle.style.display = 'block';
    });
});






/* buy offers from cart home */
// Start when the document is ready
if(document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded' , start);
}
else {
    start();
}

//  => start
function start() {
    addEvents();
}

//  => Update & Rerender
function update() {
    addEvents();
    updateTotal();
}

// => Add events
function addEvents() {
    // Change item quantity
    let cartQuantity_inputs = document.querySelectorAll('.cart-quantity');
    cartQuantity_inputs.forEach(input => {
        input.addEventListener('change', handle_changeItemQuantity);
    })
}

// => Handle events funcations
function handle_changeItemQuantity() {
    if(isNaN(this.value) || this.value < 1) {
        this.value = 1;
    }
    this.value = Math.floor(this.value); // to keep it integer
    update();
}

// => Update & Rerender funcations
function updateTotal() {
    let cartBoxes = document.querySelectorAll('.cart-box');
    let totalElement = document.querySelector('.total-price');
    let total = 0;
    cartBoxes.forEach(cartBox => {
        let priceElement = cartBox.querySelector('.cart-price');
        let price = parseFloat(priceElement.innerHTML.replace('$', ''));
        let quantity = cartBox.querySelector('.cart-quantity').value;
        total += price * quantity;
    });

    // Keep 2 digits after the decimal point
    total = total.toFixed(2);

    totalElement.innerHTML = '$' + total;
}